project:
  type: website

website:
  title: "O.G." # This will be the "O.G." logo on the left
  site-url: "https://odgarrett.github.io/"
  navbar:
    right:
      - text: about
        href: /about/
      - text: cv
        href: /cv/
      - text: publications
        href: /publications/
      - text: research
        href: /research/
      - text: scicomm
        href: /scicomm/
      - text: recipes
        href: /recipes/

format:
  html:
    theme: cosmo 
    css: ./styles.css
    toc: true
    include-after-body:
      - text: |
          <script>
            document.addEventListener('DOMContentLoaded', function() {
                // Check if a star container exists, or create one
                let starContainer = document.getElementById('star-container');
                if (!starContainer) {
                    starContainer = document.createElement('div');
                    starContainer.id = 'star-container';
                    document.body.prepend(starContainer);
                }
                
                const numStars = 150;
                for (let i = 0; i < numStars; i++) {
                    let star = document.createElement('div');
                    star.className = 'star';
                    const size = Math.random() * 2 + 1; 
                    star.style.width = `${size}px`;
                    star.style.height = `${size}px`;
                    star.style.top = `${Math.random() * 100}%`;
                    star.style.left = `${Math.random() * 100}%`;
                    starContainer.appendChild(star);
                }
            });
          </script>